### ISSUE TITLE
Concurrency access has problems with set and delete (tests fail randomly)

### ISSUE THREAD

**Issue by NikoMalik** [alphadose/haxmap#49]
I was trying to make a memory cache with auto-delete items and ran into the non-obvious problem that the tests sometimes fail

[https://github.com/NikoMalik/memoryCache](MemoryCache)

--- FAIL: TestCacheConcurrentAccess (0.07s)
    cache_test.go:113:
    
                                             /usr/lib/go-1.22/src/runtime/asm_amd64.s:1695
                Error:          Should be true
                Test:           TestCacheConcurrentAccess
                Messages:       Expected to find key
FAIL
exit status 1

--- FAIL: TestCacheConcurrentSetAndDeleteAsync (0.00s)
    cache_test.go:333:
 Error:          Should be false
                Test:           TestCacheConcurrentSetAndDeleteAsync
                Messages:       Expected not to find key
    cache_test.go:335: Expected not to find key, but found
FAIL
exit status 1
FAIL    github.com/NikoMalik/MemoryCache        0.778s

**Comment by semihbkgr** [comment]
I checked the test case in the repository you shared. It seems the flakiness is caused by the logic you implemented.

```go
var wg sync.WaitGroup

wg.Add(numGoroutines)
for i := 0; i < numGoroutines; i++ {
        go func() {
	        c.Set(key, value)
	        wg.Done()
        }()
}

wg.Add(numGoroutines)
for i := 0; i < numGoroutines; i++ {
        go func() {
	        c.Delete(key)
	        wg.Done()
        }()
}

wg.Wait()

_, found := c.Get(key)
```

I checked the test case in the repository you shared. It seems that the flakiness is caused by the logic you implemented. The result of the test entirely depends on which goroutine is executed last, which can lead to inconsistent outcomes.
